{
 "title": "gifmachine",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "cSidecar_CPUUtilization", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "cSidecar_MemoryUtilization", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Rx Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(cSidecar_RxTraffic[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Tx Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "increase(cSidecar_TxTraffic[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}