version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt update
      - apt install sudo
  pre_build:
    commands:
      - aws s3 cp s3://$ENVIRONMENT-$COMPANY-gifmachine-deploy-configs/docker/build_image.sh . --region $AWS_REGION;
  build:
    commands:
      - sh build_image.sh $ENVIRONMENT $COMPANY $AWS_REGION;
  post_build:
    commands:
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then
            echo "Build phase completed with success!";
            python3 update_taskdef_template.py $ENVIRONMENT $COMPANY $AWS_REGION;
        fi
artifacts:
  files:
    - taskdef.json
    - appspec.yaml